name: ""
title: null
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - happym2.md
theme: false
remote_theme: pages-themes/primer@v0.6.0
